CREATE TABLE [dbo].[Widget]
(
	[Id] INT IDENTITY(1,1) NOT NULL, 
    [Date] DATETIMEOFFSET NULL, 
    [Name] NVARCHAR(50) NULL, 
    [Count] INT NULL, 
    [Secret] NVARCHAR(50) NULL,
       CONSTRAINT [PK_Widget] PRIMARY KEY CLUSTERED  
   (  
   [Id] ASC  
   )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON,    ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]  
) ON [PRIMARY]  
