DROP LOGIN Widget;

CREATE LOGIN [Widget] 
	WITH PASSWORD=N'SFOG9aNHpsSjSBJrJAvrai1DbzsHbWP5MST+HdTq3KY=', 
	DEFAULT_DATABASE=[Widget], 
	DEFAULT_LANGUAGE=[us_english], 
	CHECK_EXPIRATION=OFF, 
	CHECK_POLICY=OFF
GO

ALTER LOGIN [Widget] ENABLE;

ALTER LOGIN Widget WITH PASSWORD = 'widget' UNLOCK ;
go
ALTER LOGIN Widget WITH PASSWORD = '<enterStrongPasswordHere>';
go
ALTER LOGIN Widget WITH NAME = Widget;
go

GRANT CONNECT TO [Widget]
GRANT SELECT  ON [Widget] TO [Widget];
GRANT UPDATE  ON [Widget] TO [Widget];
GRANT DELETE  ON [Widget] TO [Widget];
GRANT EXECUTE ON [Widget] TO [Widget];